language: cpp
dist: trusty
compiler:
    - clang
    - gcc
os:
    - linux
before_install:    
    - sudo add-apt-repository --yes ppa:beineri/opt-qt561-trusty
    - sudo apt-get update -qq    
    - sudo apt-get install qt56-meta-full
script:
    - source /opt/qt56/bin/qt56-env.sh
    - qmake -v
    - qmake
    - make all