language: python
sudo: required

services:
    - docker
  
matrix:
    include:
        - env: 
            - BUILD_IMAGE=razornd/mxe:qt5

script:
    docker run --rm -v $PWD:/build $BUILD_IMAGE cd build/ && i686-w64-mingw32.static-qmake-qt5 && make