#ifndef CANNYQTWRAPPER_GLOBAL_H
#define CANNYQTWRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CANNYQTWRAPPER_LIBRARY)
#  define CANNYQTWRAPPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CANNYQTWRAPPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CANNYQTWRAPPER_GLOBAL_H
